apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=dvanhu/devops-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: dvanhu/devops-backend:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8000
